const articles = [
  {
    id: 1,
    title: 'Why the U.S. War on ISIS Is Illegal',
    text: 'Weeks ago, the government filed — under seal, and not available to the public — its legal and factual reasons for holding the citizen without charge or trial. (It will be filing a public, partially redacted version soon.) Today, the ACLU filed a response, explaining why under the Constitution and laws of the United States, the government lacks the authority to continue holding our client as a military detainee. At this stage, our client is challenging only the government’s arguments concerning its legal authority to detain him assuming that he was a member of ISIS at the time of his detention. While that accusation is simply wrong — our client was actually kidnapped and imprisoned by ISIS, tried to escape, and never took up arms against the U.S. or anyone else — a detailed refutation of the government’s allegations will come at a later stage, if necessary. At this stage, because the government has not filed any criminal charges against him, litigating the government’s accusations would prolong his unlawful detention and strip him of the safeguards afforded by criminal court proceedings. The government’s arguments regarding its legal authority to detain our client are breathtaking in their scope. First, the government claims that a 2001 statute, the Authorization for Use of Military Force, gives it the power to detain our client. But that statute, which was passed in the days following 9/11, expressly limited its authorization of force to those responsible for the attacks — in other words, al-Qaida and the Taliban. Moreover, when Congress gave that authority to President Bush, it rejected the executive branch’s attempts to convince Congress to grant it open-ended authority to take military action against future threats without returning to the legislative branch.',
    author: 'Kevin Kl',
    date: '11.11.33333'
  },{
    id: 2,
    title: 'What Could Blockchain Do for Journalism?',
    text: 'David Moore is having fun. The former director of the Participatory Politics Foundation, a nonprofit open-government group that operated OpenCongress.org — a site that tracked the revolving door between Congress and lobbying and became a leading resource for government transparency — is now part of a project with an ambitious goal: finding a way to save journalism.Journalism is an industry under siege. There are, in fact, two simultaneous existential crises facing journalism: dwindling public confidence and support for media in the face of the rise in fake news and clickbait, and collapsing advertising models that supported journalism in the past. It is a pincer movement that has balkanized audiences and gutted funding.In November 2017, two New York–based sites specializing in local reportage, Gothamist (which also had outlets in other cities) and DNAinfo, were abruptly shut down by their owner, Joe Ricketts, a Trump-supporting billionaire, after their staff voted to unionize.Just weeks later, The Awl and The Hairpin, an esoteric pair of sites beloved as showcases for young writers, announced they were shuttering amid collapsing advertising revenue. A year earlier, Silicon Valley billionaire Peter Thiel was revealed to have been the secret financial backer of a devastating lawsuit that destroyed the groundbreaking gossip blog Gawker. President Trump has declared outright war on the news media, which he describes as the “enemy of the American people”; according to polling, a third of Americans agree with him.“The loss of Gothamist and DNAinfo was keenly felt,” says Moore, who lives in Brooklyn. “It prompted a sense of urgency in New York that this leading work needs wider support and strategies for sustainability.”',
    author: 'Nicky Woolf',
    date: '13.02.2018'
  },{
    id:3 ,
    title: 'Living and Dying on Airbnb',
    text: 'he rope swing looked inviting. Photos of it on Airbnb brought my family to the cottage in Texas. Hanging from a tree as casually as baggy jeans, the swing was the essence of leisure, of Southern hospitality, of escape. When my father decided to give it a try on Thanksgiving morning, the trunk it was tied to broke in half and fell on his head, immediately ending most of his brain activity.I was in bed when my mom found him. Her screams brought me down to the yard where I saw the tree snapped in two and his body on the ground. I knelt down and pulled him up by the shoulders. Blood sprayed my blue sweatshirt and a few crumpled autumn leaves. We were face-to-face, but his head hung limply, his right eye dislodged, his mouth full of blood, his tongue swirling around with each raspy breath.What do you do in this situation? I grabbed a washcloth and started mopping up his leaking face. I told my sister not to come outside. She faints when there’s blood.“Tell me each time he takes a breath,” the 911 dispatcher said in my ear.“He’s breathing in; he’s breathing out. He’s breathing in; he’s breathing out.” Saying it aloud like a mantra calmed me down slightly, but was it doing anything for him? I decided to go in for mouth-to-mouth; I ended up with a mouthful of blood.The EMTs arrived and suctioned the blood away from his face to see the damage. “He’s breathing. His heart is beating,” one of them said, “but it’s very serious.” They called for a helicopter and told us to start driving to Austin.I scrubbed the blood off my lips and took off my soaking sweatshirt. Everything was blurry — adrenaline makes things that way. So does not putting on your contacts. I popped mine into my eyes and got into the car.',
    author: 'Zak Stone',
    date: '11.11.33333'
  },{
    id: 4,
    title: 'The Web We Have to Save',
    text: 'Seven months ago, I sat down at the small table in the kitchen of my 1960s apartment, nestled on the top floor of a building in a vibrant central neighbourhood of Tehran, and I did something I had done thousands of times previously. I opened my laptop and posted to my new blog. This, though, was the first time in six years. And it nearly broke my heart.A few weeks earlier, I’d been abruptly pardoned and freed from Evin prison in northern Tehran. I had been expecting to spend most of my life in those cells: In November 2008, I’d been sentenced to nearly 20 years in jail, mostly for things I’d written on my blog.But the moment, when it came, was unexpected. I smoked a cigarette in the kitchen with one of my fellow inmates, and came back to the room I shared with a dozen other men. We were sharing a cup of tea when the voice of the floor announcer — another prisoner — filled all the rooms and corridors. In his flat voice, he announced in Persian: “Dear fellow inmates, the bird of luck has once again sat on one fellow inmate’s shoulders. Mr. Hossein Derakhshan, as of this moment, you are free.”That evening was the first time that I went out of those doors as a free man. Everything felt new: The chill autumn breeze, the traffic noise from a nearby bridge, the smell, the colors of the city I had lived in for most of my life.Around me, I noticed a very different Tehran from the one I’d been used to. An influx of new, shamelessly luxurious condos had replaced the charming little houses I was familiar with. New roads, new highways, hordes of invasive SUVs. Large billboards with advertisements for Swiss-made watches and Korean flat screen TVs. Women in colorful scarves and manteaus, men with dyed hair and beards, and hundreds of charming cafes with hip western music and female staff. They were the kinds of changes that creep up on people; the kind you only really notice once normal life gets taken away from you.Two weeks later, I began writing again. Some friends agreed to let me start a blog as part of their arts magazine. I called it Ketabkhan — it means book-reader in Persian.Six years was a long time to be in jail, but it’s an entire era online. Writing on the internet itself had not changed, but reading — or, at least, getting things read — had altered dramatically. I’d been told how essential social networks had become while I’d been gone, and so I knew one thing: If I wanted to lure people to see my writing, I had to use social media now.',
    author: 'Hossein Derakhshan',
    date: '11.11.33333'
  },{
    id: 5,
    title: 'The iPhone is Dead',
    text: 'On my iPhone 6+, most apps crash on first open. Apps freeze for 5–10 seconds whenever launched or switched to. I lose 3–4%/min on my battery and Apple Support insists that my battery is perfectly healthy. I went through “apps using significant power” and uninstalled most of them.On top of all of this, it was recently discovered that Apple is intentionally degrading the user experience based on your battery quality. Yes, they’re releasing a software update to give transparency to users and reducing the cost of a battery replacement (which is on a months-long backlog — more on Apple support later), but it feels like planned obsolescence and they’re just trying to avoid losing a class-action lawsuit.The video app is busted. Many times I record a video and all I see is a zero-second-long black frame saved. I’ve given up on taking photos because the camera app takes forever to start up and has seconds of shutter lag.This phone worked just fine three years ago. The minimal benefits of the previous iOS updates are far outweighed by the horrible user experience it’s created.I have the original Moto X (from 2013) and it still runs buttery smooth.This isn’t related to my previous iPhone, but it illustrates the lack of quality of Apple.Recently, a bottom rubber foot on my MacBook came off. It was still under AppleCare so I took it into the store, my first time to the Apple Genius Bar. They told me that AppleCare wouldn’t cover the replacement because it was cosmetic. How the rubber foot isn’t part of the laptops utility is astonishing. When you typed on it, it would wobble. To fix it, the entire bottom chassis had to be replaced, which would cost $250.I told the Apple rep that I was surprised and I’d call Apple Care later. I asked him to file a ticket for tracking and he replied that he had.',
    author: 'Musings Rand',
    date: '11.11.33333'
  },{
    id: 6,
    title: 'Why Google Should Sell Nest',
    text: 'When Google acquired Nest in 2014 it was the biggest acquisition of an energy tech company. Nest had taken the lowly thermostat and made it desirable and sexy. It was the first smart home product that made utilities think ‘customers might actually care about this stuff!’. The Nest story also became a slide in every energytech company’s fundraising pitch deck; around this period I saw at least fifty pitch decks that had Nest as a model and Google as a possible acquirer. It seemed awesome!But then it wasn’t.There was the whole Fadell-is-a-tyrant debacle after the Dropcam acquisition. Then Nest failed to ship any new products for a few years after the acquisition. Then Tony Fadell quit. And now, Nest is coming back under the Google brand. Even as the co-founder of Nest, Matt Rogers, leaves the company. At an acquisition price of $3.2Bn and cost of capital of (say) ~10% Nest should generate ~$300M of additional EBITDA to make the deal breakeven. Alphabet’s revenues from its other bets generated $794M in 2017, mostly coming from Nest, Verily and Fiber. Even if Nest generated 1/3rd of that amount, it isn’t doing the multiples of growth that Google must have been hoping for when the Nest acquisition happened. So what went wrong?A big sign of the problem with the Google acquisition of Nest was that Google/Alphabet kept releasing new connected products under its own brand name and let Nest run as a separate business. Google and, less so, Nest kept releasing compatible but non-complementary products for the smart home. This was two different companies going for it on their own. Amazon’s approach to the smart home suggests that a platform approach, with a centralized home hub, is more likely to be the winning strategy for the smart home. Amazon is owning the home with a convenience platform (Echo) and, say what you will about HomePod, Apple is experimenting with the entertainment use case for the smart home. But what is Google’s platform approach? It could have been comfort (the third of the three smart home use cases) with Nest. But that advantage is being lost because Google decided to be a ‘taker’ not a ‘giver’ in the Nest acquisition.Google has never been a hardware company. While it will go down as one of the greatest software companies of our time (with a basic business model), the idea behind the Nest acquisition was to ‘take’ expertise from Nest. This almost never works in acquisitions. Most successful M&A deals, where the integration of the acquired company into the acquirer provides the expected benefits from the acquisition, are borne out of a situation where...',
    author: 'Seyi Fabode',
    date: '11.11.33333'
  },{
    id: 7,
    title: 'Capturing the value of anomalies through postmortems',
    text: 'This is an excerpt from the Stella Report, which is the result of the first project “Coping With Complexity” performed by the Resilience Engineering In Business-Critical Software Consortium (“SNAFUcatchers”). A video introduction to the report and the consortium is here.Anomalies are unambiguous but highly encoded messages about how systems really work. Postmortems represent an attempt to decode the messages and share them. Patterns in the message content, in the frequency and timing of the messages, and in the general themes that the messages touch upon are information about the system that cannot be obtained by other methods. Complexity and change — the two are closely linked — make it impossible to maintain a complete and accurate understanding of the system. Anomalies are indications of the places where the understanding is both weak and important. Anomalies are a class of untyped pointers to deficiencies in our understanding that matter. We can, if we choose to do so, if we have sufficient skill in decoding, use those pointers to identify regions worthy of study. Doing this is not simple nor is it always obviously rewarding. But with diligent practice it is possible.Some of what we know about postmortems comes from the study of reactions to failure in other domains. Results from those studies are consistent with what we know about postmortems in IT settings and this applies to both the opportunities and challenges that come when trying to build competence and consistency in the approach to postmortems.As in other domains, postmortems are private or semi-private events intended to identify and capture important factors and features associated with anomalies. The basic premise is that postmortems promote learning from (bad) experiences so that (1) such experiences can be made less likely if their sources are eliminated or reduced and that (2) the ability to manage such experiences can be made better if responses to them are better prepared for, e.g. by technical means, better training. The fact that Allspaw and others use the term in IT settings is the result of recognition of a similarity with the processes used in medical settings and a deliberate attempt to evoke the conditions and assumptions that apply there.One participant observed: “We see repeatedly that postmortems generate I-didn’t-know-that-the-system-worked-that-way experiences.” Conducting postmortems informs and re-calibrates people’s models of the how the system works, their understandings of how it is vulnerable, and what opportunities are available for exploitation. “Collectively, our skill isn’t in having a good model of how the system works, our skill is in being able to update our model efficiently and appropriately.”*',
    author: 'John Allspaw',
    date: '11.11.33333'
  },{
    id: 8,
    title: 'Getting educational research right',
    text: 'In debates about whether education is a profession, one issue that is often raised is the extent to which there is an agreed knowledge base. In medicine, for example, there is a broad consensus that antibiotics are ineffective in treating viral infections. While doctors frequently prescribe antibiotics for viral infections, the fact that they are roundly criticised for doing this suggests a fair degree of consensus that the practice is inappropriate.In education, on the other hand, there does not seem to be any approach to educating students that commands the support of the majority of practitioners. For some, this means that education is what philosopher Thomas Kuhn called a ‘pre-science’. Education may not be a science now, but once we can agree on concepts, procedures and methods for finding things out, then education will take its place alongside physics, chemistry and biology, and produce ‘reliable knowledge’.For others, the nature of educational processes means that reliable knowledge is impossible: there will never be a ‘best’ way of teaching anything, so research is a waste of time. Some teachers may be more effective than others, but knowing about research cannot make teachers more effective.As well as being unhelpful, both of these extreme positions are in fact incorrect. While educational research can never tell teachers, leaders and policymakers what to do — the situations they face are too varied and complex — it can suggest which practices are likely to have the greatest benefits for their students, and which are likely to be less effective. However, even where such guidance is supported by the preponderance of evidence, it is important to note that it may not be applicable to all situations. As a result, teachers, leaders and policymakers need to be critical consumers of educational research.Over the last 30 years or so, as governments have sought ways to improve the achievement of young people in schools, many countries have searched for ‘what works’ in education. The logic is attractive. If only we could figure out what the most effective policies and practices are, we could implement them in every school and college. However, in reality, moving from research to practice is extremely challenging. The issue of class-size reduction provides an illuminating example.Class-size reduction is a very expensive way to improve student achievement. To figure out whether such a step would provide good value for money, we would need to find out how much extra achievement we would get. This was the logic of the Tennessee Student Teacher Achievement Ratio (STAR) study, described by Frederick Mosteller — one of the last century’s greatest statisticians — as “one of the most important educational investigations ever carried out”. Groups of 50 students were allocated, at random, either two teachers, three teachers or two teachers with teaching assistants.',
    author: 'Dylan Wiliam',
    date: '11.11.33333'
  },{
    id: 9,
    title: 'Progress in Dynamic Gas Price Estimation',
    text: 'The primary goal of ethgasstation.info is to provide reasonably accurate, real-time predictions of the time it will take for any given transaction to be confirmed on the Ethereum network. This piece of information can help wallets and users set the best gas price based on how quickly they need a confirmation and what fee they are willing to pay.Ethereum now routinely processes over 300,000 transactions per day — and ethgasstation records the block at which all transaction are first seen by its node and the block at which it is later confirmed- so there is no lack of data on which to build a predictive model. In fact, as people who are familiar with model building will know, the biggest risk in model construction with large data sets like this is overfitting- i.e. assuming there is real relationship between two variables based on statistical tests, when in fact the model is fundamentally misspecified.As I have previously written, up until recently, the transaction time prediction model used at ethgasstation included the following parameters: the transaction’s gas price, the percent of network hashpower that accept that gas price, the number of transactions at or above the transaction’s gas price in the txpool, and whether the transaction was a simple transfer (i.e. gas offered = 21,000). It turns out this while this produced reasonable predictions in many circumstances– there was an important misspecification in the model that I will now describe.If you study the ETH transaction pool today, you will notice the following phenomena: a substantial proportion of the current transaction volume comes from a relatively small number of addresses, often submitted in large batches to the network over short time intervals. Additionally, there are events like ICOs where there is a sudden surge in transactions from multiple users all going to the same address.Based on my analyses of these transactions, it appears that miners employ policies that deprioritize transactions when there are large numbers sent by or to the same address. Furthermore, they seem to prioritize address diversity even at the cost of maximizing transaction fees. For example- if there are 2000 transactions submitted from the same address with a 30 Gwei gas price, you will still see transactions with lower gas prices getting confirmed before this entire batch is processed. Whatever the motivation, this policy has the effect of keeping the network running smoothly for the average user (who is typically only sending a couple transactions at a time).These prioritization effects are very strong. In fact, once I adjusted for them in my models, it became apparent that there is no special advantage for transactions offering 21000 gas (a standard transfer) vs. higher gas contract calls. This is good news for users interacting with smart contracts.',
    author: 'ETH Gas Station',
    date: '11.11.33333'
  },{
    id: 10,
    title: 'COPYTRACK — Blockchain-based platform presenting digital copyright register',
    text: 'They expect to utilize the blockchain to construct a worldwide copyright enroll for computerized media. Huge desire yet would they be able to convey? Will I get tied up with this ICO? Discover in my Copytrack ICO survey video!In a to a great degree brief time span, COPYTRACK has developed to end up noticeably the main organization in the overall market of exceedingly mechanized copyright authorization. Beginning in Berlin and having a nearness in New York and Tokyo has enabled us to specifically draw in with craftsmen and their systems everywhere throughout the world, and has helped us to rapidly build our client base. The absence of passage obstacles guaranteed high change at all means of our procedures.At the center of COPYTRACK is the formation of a worldwide decentralized copyright enroll for advanced substance, which verifies clients and connections computerized licensed innovation. This registry will create a one of a kind biological community for rights-holders, consequently giving new e-customer commercial centers. With its bleeding edge innovation and procedures, it is appropriate to all inclusive address the key difficulties in the business and will be available to people in general.I was not paid or supported to do this video, this is my own supposition and as I am not a money related guide, this video ought not be taken as monetary counsel. Continuously contribute at your own hazard and never contribute more than you can stand to lose.',
    author: 'Greg Jones',
    date: '11.11.33333'
  }
];

export default articles